<?php
/**
 * Message translations.
 *
 * This file is automatically generated by "yii message/extract" command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of "@@" marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return
    [
        '{n, plural, other{cucumber}}' => '{n, plural, =1{Редактировать} other{Обновить}}',


        "Show «{attribute}» in category" => "Показать «{attribute}» в категории",
        "Add «{attribute}» in category" => "Добавить «{attribute}» в категорию",
        "Show «{attribute}»" => "Показать «{attribute}»",
        "Open «{attribute}»" => "Открыть «{attribute}»",
        "Edit «{attribute}»" => "Изменить «{attribute}»",
        "Create «{attribute}»" => "Создать «{attribute}»",
        "Add «{attribute}»" => "Добавить «{attribute}»",
        "Delete «{attribute}»" => "Удалить «{attribute}»",
        "Editing of {attribute}" => "Редактирование {attribute}",
        "Editing of «{attribute}»" => "Редактирование «{attribute}»",
        "View of {attribute}" => "Просмотр {attribute}",
        "View of «{attribute}»" => "Просмотр «{attribute}»",
        "view of «{attribute}»" => "Просмотреть «{attribute}»",
        "view data of «{attribute}»" => "Просмотреть данные «{attribute}»",

        "Rename" => "Переименовать",

        "Tasks" => "Задачи",
        "Operations" => "Операции",
        "Statistics" => "Статистика",

        "Data of catalog" => "Данные каталога",
        "data of catalog" => "Данных каталога",


        "Create subsection" => "Создать подраздел",
        "Change sorting" => "Поменять сортировку",

        "Categories inside category: «{attribute}»" => "Категории внутри категории: «{attribute}»",


        "Minimize" => "Свернуть",
        "Restore" => "Развернуть",

        "Actual" => "Актуальный",
        "Completed" => "Завершен",
        "Irrelevant" => "Неактуальный",
        "Tried" => "Проверенный",
        "Test" => "Проверить",
        "Blocked" => "Заблокированный",
        "Deleted" => "Удаленный",



        "highest" => "Очень Высокий",
        "high" => "Высокий",
        "middle" => "Средний",
        "low" => "Низкий",

        "checked" => "Проверенный",
        "unchecked" => "Непроверенный",


        "Extension" => "Расширение",

        "Cache File" => "Кэш Файла",
        "Name Original" => "Оригинальное Название",
        "Name New" => "Новое Название",
        "Size File" => "Размер Файла",

        "Status" => "Статус",
        "Shape" => "Состояние",
        "Checked By" => "Проверил",
        "Comment" => "Комментарии",

        "Priority" => "Приоритет",
        "Downloaded At" => "Загружено",
        "Installed At" => "Установлено",
        "Created By" => "Добавил",
        "Created At" => "Добавлено",
        "Updated By" => "Обновил",
        "Updated At" => "Обновлено",

        "Created at from" => "Добавлено От",
        "Created at till" => "Добавлено До",
        "Updated at from" => "Обновлено От",
        "Updated at till" => "Обновлено До",
        "from" => "От",
        "Till" => "До",

        "Availability" => "Наличие",
        "Status in system" => "Статус в системе",
        "Status Log" => "Статус Лога",

        "{delta, plural, =1{Document} other{Document's}} «{attribute}» <b>№ {items}</b> {delta, plural, other{modified}}" => "{delta, plural, =1{Документ} other{Документы}} «{attribute}» <b>№ {items}</b> {delta, plural, =1{изменен} other{изменены}}",

        "Complete delete of «{attribute}» #{item}" => "Полное удаление «{attribute}» #{item}",
        "Reset password of «{attribute}» #{item}" => "Сбросить пароль «{attribute}» #{item}",
        "Account deleting" => "Удаление учетной записи",

        "Reset password" => "Сбросить пароль",
        "Resetting the account password" => "Сброс пароля для учетной записи",
        "The administrator of the <b>«{attribute}»</b> group has reset your password." => "Администратор группы <b>«{attribute}»</b> сбросил ваш пароль.",
        "The administrator of system has reset your password." => "Администратор системы сбросил ваш пароль.",


        "Delete data" => "Удалить данные",
        "Change data" => "Изменить данные",
        "Change data of «{attribute}»" => "Изменить данные «{attribute}»",
        "Change data of «{attribute}» #{item}" => "Изменить данные «{attribute}» #{item}",

        "Edit" => "Изменить",
        'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
        'Are you sure you want to delete the folder with «{attribute}»?' => 'Вы уверены, что хотите удалить каталог «{attribute}»?',
        'Are you sure you want to delete the folder with ' => 'Вы уверены, что хотите удалить каталог ',
        'Are you sure you want to delete account deleting?' => 'Вы уверены, что хотите удалить учетную запись?',

        "Delete of «{attribute}» #{item}" => "Удаление «{attribute}» #{item}",
        "Undelete of «{attribute}» #{item}" => "Восстановить удаленый «{attribute}» #{item}",

        "Type" => "Вид/Тип",
        "type" => "Вид",
        "types" => "Виды",
        "Types" => "Виды/Типы",
        "Locations" => "Рассположения",
        "Location" => "Рассположение",
        "ID - Location" => "Рассположение",
        "in the current directory" => "в текущии каталог",
        "to the parent directory" => "в родительский каталог",

        "Adding data" => "Добавление",
        "Adding data of «{attribute}»" => "Добавление «{attribute}»",
        "Adding of «{attribute}»" => "Добавление «{attribute}»",
        "Adding of {attribute}" => "Добавление {attribute}",
        "Adding of «{attribute}» to the catalog" => "Добавление «{attribute}» в каталог",
        "List of {items}" => "Список {items}",
        "Automatic Control System" => "Автоматизированная Система Управления",
        "Date Action" => "Дата Действия",
        "Type Action" => "Вид Действия",
        "Created: {attribute}" => "Создан: {attribute}",
        "Creating {attribute}" => "Создание {attribute}",

        "Error restoring of <b>«{attribute}»</b>." => "Ошибка восстановления <b>«{attribute}»</b>.",
        "Document <b>«{attribute}»</b> not created." => "Документ <b>«{attribute}»</b> не создан.",
        "Document <b>No.{attribute}</b> is locked for editing." => "Документ <b>№{attribute}</b> заблокирован для редактирования.",
        "Document <b>No.{attribute}</b> has been restored." => "Документ <b>№{attribute}</b> восстановлен.",

        "(No. {item})" => "(№ {item})",
        "(To the catalog - № {item})" => "(В каталог - № {item})",

        "Report" => "Отчет",
        "Reports" => "Отчеты",
        "General report of the movements" => "Общий отчет передвижений",
        "General" => "Общий",
        "Filter" => "Фильтровать",
        "Change the phone" => "Изменить телефон",

        "Shop Url" => "Ссылка",

        "Rating by \"alexa.com\"" => "Рейтинг по \"alexa.com\"",
        "Ratings" => "Рейтинги",
        "Personal of rating" => "Личный рейтинг",

        "Update" => "Обновить",
        "Search" => "Найти",
        "Search by parameters" => "Поиск по параметрам",

        "ID From" => "От ID",
        "ID Till" => "До ID",

        "Reset" => "Сбросить",
        "Contact us" => "Контакты",
        "Log in" => "Войти",
        "Entrance" => "Войти",
        "Sign In" => "Авторизоваться",
        "log in" => "Авторизоваться",
        "Log out" => "Выход",
        "recover password" => "восстановить пароль",
        "Recover password" => "Восстановить пароль",
        "Registration in the system" => "Регистрация в системе",

        "Failed to remove «{attribute}»" => "Ошибка удаления «{attribute}»",
        "Failed to save «{attribute}»" => "Ошибка сохранения «{attribute}»",
        "«{attribute}» is not implemented." => "«{attribute}» не будет реализован.",

        "Role of user" => "Роль пользователя",
        "role of user" => "Роли пользователя",
        "Roles of user" => "Ролей пользователя",
        "The User" => "Пользователя",
        "user" => "Пользователя",

        'Page not found or are restricted for you.' => 'Страница не найдена или ограничена для вас.',
        'Page not found.' => 'Запрашиваемая страница не найдена.',
        'Invalid element type.' => 'Неверный тип элемента.',

        "Phone" => "Телефон",
        "phone" => "Телефона",
        "E-mail" => "E-mail",
        "Site" => "Сайт",
        "Rate limit exceeded." => "Все попытки входа исчерпаны.",


        "Bank" => "Банк",
        "This «{attribute}» has been added" => "Этот «{attribute}» уже был добавлен",
        "«{attribute}» cannot be blank." => "Необходимо заполнить «{attribute}».",
        "Fill in the «{attribute}»." => "Заполните «{attribute}».",
        "Enter the «{attribute}»." => "Введите «{attribute}».",

        "English" => "Английский",
        "Russian" => "Русский",
        "Language" => "Язык",

        "Information" => "Информация",
        "Home" => "Главная",
        "Security" => "Безопасность",
        "Message" => "Сообщение",
        "Users" => "Пользователи",
        "User List" => "Список пользователей",
        "Authentication data" => "Аутентификационные данные",
        "All users" => "Все пользователи",
        "Save" => "Сохранить",
        "Create" => "Создать",
        "Delete" => "Удалить",
        "Active" => "Активный",
        "Inactive" => "Неактивный",
        "Apply" => "Применить",
        "Cancel" => "Отменить",
        "List" => "Список",
        "Add" => "Добавить",
        "Access rights" => "Права Доступа",
        "Access rule" => "Правило Доступа",
        "access rule" => "Правила Доступа",
        "Operation" => "Операция",
        "Task" => "Задача",
        "Assign role" => "Назначить роль",
        "Role" => "Роль",
        "Role of element" => "Роль элемента",
        "Serialize" => "Сериализация",
        "Children of elements" => "Дочерние элементы",
        "Nested of catalog" => "Вложенного каталоги",
        "Role in system" => "Роль в системе",
        "Root role" => "Полные прова",
        "Roles" => "Роли",
        "All roles" => "Все роли",
        "Choose items" => "Выбирите элементы",
        "Clear cache and temporary files" => "Очистить кэш и временные файлы",
        "Clear cache" => "Очистить кэш",
        "Require a change of password in the next sign in" => "Требовать смены пароля при следующем входе в систему",
        "Auto-generate password" => "Авто-генерация пароля",


        "List of phone" => "Список телефонов",
        "Welcome" => "Добро пожаловать",

        "Official website" => "Офицальный сайт компании",
        "Elements" => "Элементы",
        "Element" => "Элемент",
        "element" => "элемента",

        "Subject" => "Тема сообщения",
        "To" => "Кому",
        "From" => "От кого",
        "Body" => "Письмо",

        "Remember me" => "Запомнить меня",
        "Login" => "Логин",
        "Password" => "Пароль",
        "login" => "Логином",
        "password" => "Паролем",
        "Incorrect password." => "Некорректный пароль.",
        "Incorrect username or password." => "Некорректный логин или пароль.",
        "New password has been changed." => "Новый пароль был изменен.",
        "Submitted" => "Отправлено",
        "Not sent" => "Не отправлено",
        "Check your email address" => "Проверьте ваш E-mail",
        "Failed send email" => "Не получилось отправить E-mail",
        "Send" => "Отправить",
        "A link to the password recovery will be sent to the post office." => "Ссылка на восстановление пароля, будет отправлена на почту.",
        "Change password" => "Изменение пароля",
        "Please enter your new password." => "Пожалуйста, введите новый пароль.",
        "Name" => "Название",
        "Profile" => "Профиль",
        "My profile" => "Мой профиль",
        "my profile" => "Моего профиля",
        "Auth Key" => "Ключ Авторизации",


        "Return to site" => "Вернуться на сайт",


        "New Password" => "Новый пароль",
        "New Password Confirm" => "Подтверждение пароля",
        "Confirm password" => "Подтверждение пароля",
        "New passwords do not match" => "Новые пароли не совпадают",
        "User not found" => "Пользователь не найден",
        "Verification Code" => "Проверочный Код",
        "Homepage" => "Домашняя страница",
        "Go back to main page" => "Вернуться на главную страницу",
        "Token reset password is invalid." => "Токен сброса пароля недействительный.",
        "Token reset password can not be empty." => "Токен сброса пароля не может быть пустым.",

        "Thank you for contacting us. We will reply to you as soon as possible." => "Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.",
        "Please note that if you turn Yii debugger, you must have the ability to view e-mail messages on the mail debugger panel." => "Обратите внимание, что если вы включите отладчик Yii, вы должны иметь возможность просматривать сообщения электронной почты на почтовом панели отладчика.",
        "If you have any questions or suggestions, please use the form contact us." => "Если у вас возникли вопросы или предложения, пожалуйста воспользуйтесь формой обратной связи.",
        "Since the application is in development mode, e-mail is not sent but saved in file <code>{fileTransportPath}</code>. Please adjust the <code>useFileTransport</code> and <code>mail</code> application component, to enable the sending of on email." => "Поскольку приложение находится в режиме разработки, электронная почта не отправляется, но сохраняется в файл <code>{fileTransportPath}</code>. Пожалуйста, настройте <code>useFileTransport</code> и <code>mail</code> компонент приложения, чтобы включить отправку по электронной почте.",
        "Feedback form" => "Форма обратной связи",
        "Registered" => "Зарегистрирован",
        "ID - User" => "ID - Пользователя",
        "Notice Email" => "Email - уведомления",
        "Notice SMS" => "SMS - уведомления",
        "Confirmed user" => "Подтвержденный пользователь",
        "Confirmed By" => "Подтвердил",
        "Hash password" => "Хэш пароля",
        "Token reset password" => "Токен сброса пароля",
        "Notification to email" => "Уведомление по email",
        "Send to mail" => "Отправить на почту",
        "When processing your request an error occurred." => "При обработки вашего запроса произошла ошибка.",
        "Please inform us about an error, if you think this is an error on the server side!" => "Пожалуйста сообшите нам об ошибке, если думаете что это ошибка на стороне сервера!",


        "Connect with us" => "Связаться с нами",
        "Sincerely,<br /> Administration of information system." => "С Уважением,<br /> Администрация информационной системы.",


        "To reset your password, click" => "Чтобы восстановить свой пароль, нажмите",
        "on the link" => "на ссылку",

        "ID - Profile" => "ID - Профиля",
        "ID - Phone" => "ID - Телефона",
        "First Name" => "Имя",
        "Last Name" => "Фамилия",
        "Patronymic" => "Отчество",
        "Gender" => "Пол",
        "Full name" => "ФИО",
        "full name" => "Полное название",

        "Short name" => "Инициалы",
        "Department" => "Отдел",
        "Female" => "Женский",
        "Male" => "Мужской",

        "Note" => "Примечание",
        "Attention!" => "Внимение!",
        "Forbidden" => "Запрещено",
        "Successful" => "Успешно",
        "Successfully" => "Успешно",
        "Unsuccessful" => "Неудачно",
        "The data is saved" => "Данные сохранены",
        "The data is not saved" => "Данные не сохранены",
        "You don't have permission to perform this action" => "У вас нет разрешения на выполнение этого действия",
        "Create a «{attribute}»" => "Создать «{attribute}»",
        "Change a «{attribute}»" => "Изменить «{attribute}»",

        "The system added of «{attribute}»: <strong>{fullName}</strong>." => "В систему добавлено «{attribute}»: <strong>{fullName}</strong>.",
        "Changing data of «{attribute}»: <strong>{fullName}</strong>." => "Изменение данных «{attribute}»: <strong>{fullName}</strong>.",
        "Changing data of <strong>«{attribute}»</strong>." => "Изменение данных <strong>«{attribute}»</strong>.",

        "<strong>«{fullName}»</strong> removed from the system" => "<strong>«{fullName}»</strong> удален из системы",
        "<strong>«{FullName}»</strong> removed from the system" => "<strong>«{FullName}»</strong> удалены из системы",
        "<strong>«{fullName}»</strong> not removed from the system" => "<strong>«{fullName}»</strong> не удален из системы",

        "{nameType} <strong>{fullName}</strong> registered in the system" => "{nameType} <strong>«{fullName}»</strong> зарегистрирован в системе",
        "{nameType} <strong>{fullName}</strong> not registered in the system" => "{nameType} <strong>«{fullName}»</strong> не зарегистрирован в системе",
        "{nameType} <strong>{fullName}</strong> removed from the system" => "{nameType} <strong>{fullName}</strong> удален из системы",
        "{nameType} <strong>{fullName}</strong> not removed from the system" => "{nameType} <strong>{fullName}</strong> не удален из системы",
        "{nameType} <strong>{fullName}</strong> Removed from the system" => "{nameType} <strong>{fullName}</strong> удалена из системы",
        "{nameType} <strong>{fullName}</strong> not Removed from the system" => "{nameType} <strong>{fullName}</strong> не удалена из системы",

        "Register {attribute} #{item}" => "Зарегистрировать {attribute} #{item}",
        "Register «{attribute}» in system" => "Зарегистрировать «{attribute}» в системе",

        "This «{attribute}» is already in use" => "Этот «{attribute}» уже исспользуется",
        "Carrying out the document of «{attribute}»" => "Проведение документа «{attribute}»",
        "Change the document of «{attribute}» #{item}" => "Изменение документа «{attribute}» #{item}",
        "Change the document of «{attribute}»" => "Изменение документа «{attribute}»",
        "Change the document" => "Изменение документа",

        "Carrying out the document" => "Проведение документа",
        "Document of «{attribute}»" => "Документ «{attribute}»",
        "Documents of «{attribute}»" => "Документы «{attribute}»",

        "Country" => "Страна",
        "Russia" => "Россия",

        "It should be noted the default phone for the user" => "Необходимо отметить основной телефон пользователя",
        '{attribute} should be noted.' => 'Необходимо отметить «{attribute}».',
        '{attribute} should be choose.' => 'Необходимо выбрать «{attribute}».',

        "Logo Company" => "Логотип Компании",
        "Site Company" => "Сайт Компании",

        "Back" => "Назад",
        "Save and go back" => "Сохранить и вернуться",
        "Edit and go back" => "Изменить и вернуться",
        "Remove this item" => "Удалить позицию",
        "Basic phone" => "Основной телефон",
        "Basic" => "Основной",
        "Phone numbers" => "Телефонные номера",
        "Phone number" => "Телефонный номер",
        "Number of phone" => "Номер телефона",
        "Type of phone" => "Тип телефона",
        "Default settings" => "Настройки по умолчанию",
        "Status of phone" => "Статус телефона",
        "Template of phone" => "Телефон",
        "Reference of phone" => "Шаблон телефона",
        "Mobile" => "Сотовый",
        "Landline" => "Стационарный",
        "Fax" => "Факс",
        "Available" => "Доступен",
        "Unavailable" => "Недоступен",
        "Error" => "Ошибка",
        "Unexpected error" => "Неожиданная ошибка",

        "No files found to update the database" => "Не найдено файлов для обновления базы данных",
        "The catalog is empty" => "Каталог пустой",

        "Catalogs" => "Каталоги",
        "Catalog" => "Каталог",
        "The catalog" => "Каталог",
        "catalog" => "Каталога",
        "Yes" => "Да",
        "No" => "Нет",
        "Not end" => "Не завершен",
        "Select agents" => "Добавить реагент",

        "Editing" => "Редактирование",
        "the directory" => "каталога",
        "The Directory" => "Каталога",
        "a directory" => "каталога",
        "in directory" => "в каталог",
        "the root directory" => "корневого каталога",

        "File" => "Файл",


        "Your profile" => "Ваш профиль",
        "Exit" => "Выход",
        "To block" => "Заблокировать",
        "Request for password recovery" => "Запрос на восстановление пароля",
        "Please, enter your email." => "Пожалуйста, введите вашу электронную почту.",
        "Sections" => "Разделы",
        "Section" => "Раздел",

        "User" => "Пользователь",
        "Approved" => "Подтвержден",
        "Storage" => "Хранилище",


        "Address" => "Адрес",
        "Logged At" => "Время последней авторизации",
        "Last Activity At" => "Время последней активности",
        "Last Activity In The Admin At" => "Время последней активности в админке",
        "Image" => "Фото",

        "Username or Email" => "Логин или Email",
        "The request to change the password for" => "Запрос на смену пароля для ",
        "This login is already in use by another user." => "Этот логин уже занят другим пользователем.",
        "There is no registered user with that email." => "Нет зарегистрированного пользователя с таким E-mail.",
        "Password reset for " => "Восстановление пароля для ",
        "Sign up at site" => "Регистрация на сайте ",
        "Sign up" => "Зарегистрироваться",
        "Saved" => "Сохранено",
        "Could not save" => "Не удалось сохранить",
        "No records found" => "Записи не найдены",
        "Mission complete" => "Задание выполнено",

        "system administration" => "система администрирования",
        "Main" => "Основное",

        "Access" => "Доступ",
        "Files" => "Файлы",
        "Images" => "Изображения",
        "Content" => "Контент",
        "Notes" => "Заметки",
        "Default Menu" => "Стандартное меню",

        "Username" => "Пользователь",
        "Description" => "Описание",
        "Delete the selected items" => "Удалить выбранные элементы",

        // Таблица перевода для эндоскопии
        "Endoscope Base" => "База Эдоскопов",
        "Tools" => "Инструменты",
        "tools" => "Инструментов",
        "tool" => "Инструментом",
        "Tool" => "Инструмент",
        "TooL" => "Инструмента",
        "Cleaning Tools" => "Инструменты Очистки",
        "Cleaning Tool" => "Инструмент Очистки",
        "Cleaning tool" => "Инструмента Очистки",
        "Cleaning Agents" => "Средства Очистки",
        "Cleaning Agent" => "Средство Очистки",
        "Tags and links" => "Метки и связи",
        "Cleaning Logs" => "Журналы Очистки",
        "Cleaning Log" => "Журнал Очистки",
        "Cleaning log" => "Журнала Очистки",
        "Cleaning Levels" => "Уровни Очистки",
        "Cleaning Level" => "Уровень Очистки",
        "Cleaning level" => "Уровня Очистки",
        "Icon" => "Иконки",
        "Machined Tool" => "Обрабатываемый Инструмент",

        "Instrument Statuses" => "Статусы инструментов",
        "Instrument Status" => "Статус инструмента",
        "Instrument status" => "Статуса инструмента",

        "Status Tied" => "Статус Привязки",
        "STatus" => "Статуса",
        "status" => "Статусом",
        "Rfid Tags" => "Rfid Метки",
        "Rfid Tag" => "Rfid Метка",
        "Complete data" => "Полные данные",
        "Coded Key r-fid" => "Кодовый ключ",

        "Staff" => "Сотрудники",
        "staff" => "Сотрудником",
        "stafF" => "Сотрудника",
        "employee" => "Сотрудника",
        "Employee" => "Сотрудник",
        "The employee" =>  "Сотрудник",

        "Endoscope cleaning accounting system" => "Ситема учета очистки эндоскопов",
        "Fixed By" => "Зафиксирован, За",

        "Selected item have been removed from the system" => "Выбранный элемент удалены из системы",
        "Selected items have been removed from the system" => "Выбранные элементы удалены из системы",
        "Failed to delete the selected item" => "Не удалось удалить выбранный элемент",
        "Failed to delete the selected items" => "Не удалось удалить выбранные элементы",

        "Mode of operation" => "Режим работы",
        "General of data" => "Общие данные",
        "List of staff" => "Список Сотрудников",

        "Solution Name" => "Название раствора",
        "Solution concentration" => "Концентрация раствора",
        "Solution temperature" => "Температура раствора",
        "Staff By" => "Сотрудником",
        "Add Data" => "Дата Операции",
        "Tools By" => "Очистка Инструмента",
        "Choose the «{attribute}»." => "Выбирите «{attribute}».",
        "Employee management" => "Управление Сотрудниками",

        "Add tool" => "Добавление инструмента",
        "Leak test" => "Тест на Герметичность",
        "Final cleaning" => "Окончательная Очистка",
        "Quality of cleaning" => "Качество Очистки",
        "Manual disinfection" => "Ручная Дезинфекция",

        "Manual" => "Ручная",
        "Auto" => "Автоматическая",

        "Auto disinfection" => "Авто Дезинфекция",
        "Tool cleaning" => "Чистка Инструмента",

        "Level 1.2 «Add tool»" => "Ур.1.2 «Добавление инструмента»",
        "Level 1.1 «Add staff»" => "Ур.1.1 «Добавление сотрудника»",
        "Level 2 «Leak test»" => "Ур. 2 «Тест на герметичность»",
        "Level 3 «Final cleaning»" => "Ур. 3 «Окончательная очистка»",
        "Level 4 «Quality of cleaning»" => "Ур. 4 «Качество очистки»",
        "Level 5 «Manual disinfection»" => "Ур. 5 «Ручная Дезинфекция»",
        "Level 5 «Auto disinfection»" => "Ур. 5 «Авто Дезинфекция»",
        "Level 6 «Tool cleaning»" => "Ур. 6 «Чистка инструмента»",

        "Start Cleaning" => "Начало Очистки",
        "End Cleaning" => "Завершение Очистки",
        "Date «Cleaning Quality Check»" => "Дата «Проверки Качества Очистки»",
        "Status «Cleaning Quality Check»" => "Статус «Проверки Качества Очистки»",

        "Type «Disinfection»" => "Тип «Дезинфекции»",
        "Auto «Disinfection»" => "Автоматическая «Дезинфекция»",
        "Manual «Disinfection»" => "Ручная «Дезинфекция»",

        "Start «Disinfection»" => "Начало «Дезинфекции»",
        "End «Disinfection»" => "Завершение «Дезинфекции»",
        "Start «Tool cleaning»" => "Начало «Очистка Инструмента»",
        "End «Tool cleaning»" => "Завершение «Очистка Инструмента»",


    ];